### ISSUE TITLE
Fails to compile with ReShade 5.9.2

### ISSUE THREAD

**Issue by Morbad** [Filoppi/PumboAutoHDR#3]
[03120] | ERROR | Failed to compile "\reshade-shaders\Shaders\AdvancedAutoHDR.fx":
\reshade-shaders\Shaders\Color.fxh(25, 8): error X3004: undeclared identifier 'v'

**Comment by pgirzalsky** [comment]
@Morbad @Filoppi You can fix the error by opening the file Color.fxh with any code/text editor and change ` return v;` in line 25 to ` return color;`.

**Comment by Filoppi** [comment]
Fixed
