### ISSUE TITLE
HDR is oversaturated and dark

### ISSUE THREAD

**Issue by joonpark72** [Filoppi/PumboAutoHDR#5]
Hello, Thanks for this mod first of all.
Decided to try HDR using dxvk a try and downloaded your shader and loaded up.  Then matched max nit value to that of my screen, 500.  Things become way to saturated and dark for gameplay.  What numbers can I tweak to make it come out less saturated and brighter on my 500nit, 10bit display?

**Comment by Filoppi** [comment]
If you use the default AutoHDR mode and just change the peak brightness there won't be any increase in saturation. Are you sure your display is running in HDR?

**Comment by joonpark72** [comment]
Yes I am running it on HDR monitor.  The game in question is Fallout New
Vegas (Tale of Two Wastelands).

Best regards,
Joonho Park

**Comment by Filoppi** [comment]
You need DXVK btw. Please join our discord and ask for help there.

**Comment by joonpark72** [comment]
Yes I am using DXVK with HDR output and will try the discord.

Best regards,
Joonho Park
